### ISSUE TITLE
would be nice to add some info to README.md

### ISSUE THREAD

**Issue by fdiblen** [thomasgibson/t3motr#1]

**Comment by TasminS** [comment]
Resolved in 34a8e62dc1db22d5276c53496904bdefb6a466a2.

**Comment by thomasgibson** [comment]
Issue not resolved. Fix incoming.

**Comment by fdiblen** [comment]
you need to remove readme.md and add its content to README.md

**Comment by thomasgibson** [comment]
Fixed in 6f663b9716cd5dedb0cc643bb0f943bc4593594b
